### ISSUE TITLE
Datensets vor dem 06/04?

### ISSUE THREAD

**Issue by michaelwaltenberger** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#12]
Hallo, könntest du erklären warum Daten für den 01/04/2020, 03/04/2020 und 05/04/2020 verfügbar sind obwohl RKI auf ihrer webpage (https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74) sagt das Datenset wurde erst am 06/04/2020 erstellt. Außerdem frage ich mich warum der 02/04 und 04/04 fehlen.

**Comment by CharlesStr** [comment]
Hallo,
gute Frage. Auf jeden Fall sind die Daten vom 01.04, 03.04. 05.04 von der Seite, die Arcgi jeden Tag erstellt. die Fehlenden Daten im April wurden wohl nicht zum Download bereitgestell. Siehe auch

https://github.com/ihucos/rki-covid19-data/releases?after=2020-04-08

Das RKI veröfffentlich Covid19 Fallzahlen schon seit März. siehe auch

https://de.wikipedia.org/wiki/COVID-19-Pandemie_in_Deutschland/Statistik
und z.B.

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/2020-03-04-de.pdf?__blob=publicationFile

Der Datensatzaufbau der Dateien im April war etwas ungenau da siech die DatenFelder manchmal geaendert haben.

Beste Grüße,

Charles
