### ISSUE TITLE
Hat jemand ein sauberes Interpretationsschma für die Datenangaben pro Datensatz?

### ISSUE THREAD

**Issue by gottfriedhelms** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#13]
Ich habe mir jetzt die rki-Definitionen durchgelesen, aber es wird mir nicht deutlich, wie ich die Datensätze, zeilenweise, verstehen kann.              

Z. B. haben wir Angaben für die Altersgruppe und für das Geschlecht, sowie für den Landkreis (außerdem für das "Meldedatum", aber lassen wir das hier).     
Dann steht "Fallzahl: Anzahl Fälle in der jeweiligen Gruppe".                    

Auf was bezieht sich hier "Gruppe"? Ort, Alter, Geschlecht, oder alles zu sammen? Und für welchen Zeitstempel - z.B. am 1. Sept sind  einige aufeinanderfolgende Nennungen mit gleicher Altersgruppe, meistens Fallzahl=1, manchmal Fallzahl=2.       

![grafik](https://user-images.githubusercontent.com/33901438/96374126-28e4ec00-1171-11eb-8698-04f8e1674ea5.png)

Also, hat jemand einen Verarbeitungsalgo / sql-anweisung, z.B. für "Anzahl Neuansteckungen Kassel 1.9.2020" ? (Würde mir das gerne aus einer Access-Tabelle lesen)

**Comment by CharlesStr** [comment]
Hallo gottfriedhelms,

mit der Datei vom 01.0.9.2020 habe ich die anzahl der Neuansteckungen wie folgt ermittelt:

SELECT RkI_FallZ.Datenstand, RkI_FallZ.Landkreis, Sum(RkI_FallZ.AnzahlFall) AS SummevonAnzahlFall
FROM RkI_FallZ
WHERE (((RkI_FallZ.NeuerFall)=1 Or (RkI_FallZ.NeuerFall)=-1))
GROUP BY RkI_FallZ.Datenstand, RkI_FallZ.Landkreis
HAVING (((RkI_FallZ.Landkreis)="LK Kassel"));


Beste Grüße Charles

**Comment by CharlesStr** [comment]
Das Ergebnis: Anzahl Faelle war 6

**Comment by CharlesStr** [comment]
Faelle gesamt pro Tag mit der jeweiligen Tagesdatei

SELECT RkI_FallZ.Datenstand, Sum(RkI_FallZ.AnzahlFall) AS SummevonAnzahlFall
FROM RkI_FallZ
WHERE (((RkI_FallZ.NeuerFall)=0 Or (RkI_FallZ.NeuerFall)=1))
GROUP BY RkI_FallZ.Datenstand;

Todesfaelle pro Tag

SELECT RkI_FallZ.Datenstand, Sum(RkI_FallZ.AnzahlTodesfall) AS SummevonAnzahlTodesfall
FROM RkI_FallZ
WHERE (((RkI_FallZ.NeuerTodesfall)=0 Or (RkI_FallZ.NeuerTodesfall)=1))
GROUP BY RkI_FallZ.Datenstand;

Genesen pro Tag

SELECT RkI_FallZ.Datenstand, Sum(RkI_FallZ.AnzahlGenesen) AS AnzahlGenesen
FROM RkI_FallZ
WHERE (((RkI_FallZ.NeuGenesen)=1 Or (RkI_FallZ.NeuGenesen)=-1))
GROUP BY RkI_FallZ.Datenstand;

**Comment by gottfriedhelms** [comment]
Ah, danke CharlesStr, das hilft weiter... Vielleicht bekomme ich ja mit deinen Tips eine wasserdichte Interpretation der Eingaben in die Felder eines Datensatzes zusammen...
