### ISSUE TITLE
Daten aus Webservice zusätzlich?

### ISSUE THREAD

**Issue by strubbi77** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#15]
Hallo, 

unter https://survstat.rki.de/Content/Query/Create.aspx kann man granularer die Daten Abfragen. 
Hat jemand diese Daten schon in nutzbarer Form vorliegen?

Grüße Strubbi

**Comment by Schmidtpk** [comment]
Sind die Daten von survstat strikt granularer? Sie haben mehr Alterskategorien, aber die Daten hier enthalten Referenzdatum und Meldedatum fuer einzelne Fälle. Bekommt man bei survstat nur das eine oder das andere?

**Comment by strubbi77** [comment]
Zusätzlich zum Alter auf Jahresebene gibt es noch 4 Falldefinitionskategorien als zusätzliche Merkmale. Für diese Merkmale granularer. 

Über die Nutzung der Filter kann man Landkreis x Geschlecht x Alter(1) x Falldefinitionskategorie x Meldewoche Gesundheitsamt erhalten. Mit dem täglichen Download noch Meldedatum RKI. 

In den Daten hier sind es: Landkreis x Geschlecht (3) x Alter(grob) x IstErkrankungsbeginn x Meldedatum x Refdatum x IstTodesfall

Ich fände es als Ergänzung evtl. hilfreich.

**Comment by CharlesStr** [comment]
Interessante Seite, Danke.
