### ISSUE TITLE
Allgemeine Frage zum Datensatz

### ISSUE THREAD

**Issue by felixpk** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#16]
Hallo @CharlesStr ,
ich arbeite gerade an einem python tool welches unter anderem die neuen Fälle pro Tag anzeigt:

![daily_cases_2020-11-07](https://user-images.githubusercontent.com/6123024/98439549-dc972700-20f2-11eb-9bed-6e570916f3e3.png)

Ich frage mich warum das RKI gestern [~21.000 neue Fälle](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html) gemeldet hat, mein tool jedoch unter 15.000 anzeigt (letzter Balken - 6.11.). Hast du eine Idee woran das liegen kann? Ist es generell möglich mit dem jeweils [aktuellen Datensatz](https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74) auf dieselben Zahlen zu kommen wie das RKI im ersten link?

Entschuldige bitte das ich das Issue hier für eine solche Frage ausnutze.
Ich würde mich freuen wenn du mir weiterhelfen könntest!

**Edit:** Ich sehe gerade das ich auf genau die selben Ergebnisse komme wie im RKI Dashboard.

**Comment by CharlesStr** [comment]
Hallo Felix, 
ist ok.

Ich benutze ACCESS und ermittle den aktuellen Stand der Fallzahlen folgend
 SQL: 

SELECT RkI_FallZ.Datenstand, Sum(RkI_FallZ.AnzahlFall) AS AnzahlFall
FROM RkI_FallZ
WHERE (((RkI_FallZ.NeuerFall)=0 Or (RkI_FallZ.NeuerFall)=1))
GROUP BY RkI_FallZ.Datenstand;

Dann importiere ich die Daten nach EXCEL und ermittle die Tagessumme der Fallzahlen indem ich den Vortag vom aktuellen Tag 
abziehe. So komme ich immer punktgenau auf die Fallzahlen des RKI

Wichtig ist die Bedingung 

NeuerFall = 0 or Neuer Fall = 1

Zur Kontrolle gehe ich auf die Seite von WIkI

https://de.wikipedia.org/wiki/COVID-19-Pandemie_in_Deutschland/Statistik#cite_note-Bericht04112020-248

in der ganz rechten Spalte ist dann auch immer ein Verweis auf die jeweilige Datengrundlage des RKI.

Beste Grüße
Charles

**Comment by felixpk** [comment]
Hallo Charles, vielen Dank für deine Antwort.
Sehe ich es denn dann richtig das ich mit der CSV-Datei (aktuellste Version) keine Rückschlüsse mehr auf die FallZahl Differenz der Vortage machen kann?
Werden hier deshalb alle CSV-Dateien separat gespeichert?

**Comment by CharlesStr** [comment]
Ja die Erfahrung habe ich gemacht. Das RKI aktualisiert bestehende Daten (durch Nachmeldungen). Deshalb sind die separat gespeicherten Daten ein genaues Abbild des jeweiligen Tages.
