### ISSUE TITLE
Files for 2020-04-05, 2020-05-05, 2020-10-06, 2020-12-09 und 2020-12-25 missing

### ISSUE THREAD

**Issue by ferraronga** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#17]
I believe the file for the day 9th of December 2020 is missing. Was there no file for that day?

Edit: not just one day is missing. I could not find the following days:
2020-04-05
2020-05-05
2020-10-06
2020-12-09
2020-12-25 (probably coming)

**Comment by CharlesStr** [comment]
Hallo ferraronga,

Ja, es fehlen mir 2020-04-05 und 2020-10-06, die restlichen Dateien sind jetzt vorhanden.
Yes, I am missing 2020-04-05 and 2020-10-06, the rest of the files are now available.

Es gibt auch noch eine andere Seite mit Daten 
There is also another page with data 

https://github.com/ihucos/rki-covid19-data/releases

**Comment by CharlesStr** [comment]
wobei das Datum ist ein UNIX Format, siehe folgenden Datensatz
where the date is a UNIX format, see the following record

IdBundesland,Bundesland,Landkreis,Altersgruppe,Geschlecht,AnzahlFall,AnzahlTodesfall,ObjectId,Meldedatum,IdLandkreis,Datenstand,NeuerFall,NeuerTodesfall,Refdatum,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Altersgruppe2
1,Schleswig-Holstein,SK Flensburg,A00-A04,M,1,0,1,**1601424000000**,01001,"23.12.2020, 00:00 Uhr",0,-9,**1601424000000**,0,1,0,Nicht übermittelt

**Comment by ferraronga** [comment]
Hallo Charles, ich habe die von 06-10-2020 heruntergeladen, das UTC-Datum umgewandelt und hier hochgeladen:
https://we.tl/t-7lzVA24v4L

Prüf mal ob so passt.

Die vom 2020-04-05 werden wir wohl nie finden. Die Hoffnung stirbt aber zuletzt!

**Comment by CharlesStr** [comment]
Das denke ich auch und danke für die Datei.
