### ISSUE TITLE
Request to rename folders

### ISSUE THREAD

**Issue by rogerlord** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#18]
Hi - I rely on your repository (and that of some others, such as https://github.com/micb25/RKI_COVID19_DATA/ to nowcast the number of positive tests in Germany, see my repo at https://github.com/rogerlord/covid-19.

Not a big issue, but it would help my code if the folder structure would be slightly different and the same across years - now you have:

* Name of month, with capital first letter - for all months in 2020
* Name of month, without a capital for the first letter + 2021 for the first month in 2021

Could you rename all folders to have the same structure, e.g.:
* Name of month, capital first letter + year

Thanks!

**Comment by CharlesStr** [comment]
The directories of the data are stored in the format MonthYYY.

Example: 
Januar2021 - Februar2021- Maerz2021
Januar2022 - Februar2022- March2022 

The directories for the year 2020 from March to December remain so.

**Comment by rlordcardano** [comment]
That works for me - thanks!

**Comment by rogerlord** [comment]
That works for me, thanks!
