### ISSUE TITLE
Benennung Files

### ISSUE THREAD

**Issue by strubbi77** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#2]
Dateinamen bitte am besten im ISO Forlmat: YYYY-MM-DD

**Comment by icestorm972** [comment]
Das habe ich auch bemerkt. Hab das GitProjekt geforkt, die Namen angepasst, ein paar Korrekturen vorgenommen (Dateiname != Datenstand in Datei zum Teil), fehlende die ich hatte ergänzt, und einen Pull-Request (siehe #1 unten) dazu gestartet...

Fork:
- https://github.com/icestorm972/CSV-Dateien-mit-Covid-19-Infektionen-

Pull-Request:
- https://github.com/CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-/pull/1

**Comment by strubbi77** [comment]
Hab ich nachdem ich es geschrieben hatte auch bemerkt. Hab mich dann aber erstmal um die Files gekümmert, die ich noch zusätzlich gefunden hatte.

**Comment by CharlesStr** [comment]
Prima, daß ich so schnell Hilfe finde. Mir ist auch aufgefallen die Feldnamen sind in einigen Dateien unterschiedlich benannt. Auch wurde die ObjectId in FID geändert. 
Ich bin nun neu auf GitHub. Ein Pull-Reauest bedeutet die Änderungen werden übenommen? 

Wie verarbeitet ihr die dadten weiter? Ich verwende Access und Excel.

**Comment by icestorm972** [comment]
Excel365 mit Power Query, funktioniert zur Zeit aber nur mit dem aktuellsten CSV-Format, da ich jedesmal einfach den m-Code neu angepasst hatte :-/

Schaue mir da für mich hauptsächlich die Entwicklung der neuen Fallzahlen/Tag und einem Reff ohne kompexere Imputierung* oder Nowcasting** rückblickend an, gerade in Bezug auf Massnahmen.

*) Nehme entweder RefDatum, falls bekannt, oder nehme den Medianverzug von 7 Tagen zum Meldedatum an (wird ja eh gefiltert danach).
**) Schneide einfach die letzten 14 Tage der Ergebnisse ab, da die Daten noch nicht aussagekräftig sind.
