### ISSUE TITLE
mistakes in files

### ISSUE THREAD

**Issue by SamiKam** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#20]
- just for information
- there are some mistakes in the files for 03/17/2021 and 03/18/2021 - in both files the year of Datenstand is 2020.
In 03/19/2021 the Datenstand is good again, but there the comma is missing as separator between IdLandkreis Datenstand.

but great work and thank you very much to keep the archive uptodate and help keeping track in this "mess" of daily data  

Cheers

**Comment by CharlesStr** [comment]
Thank You for this information. i Correct this mistake
