### ISSUE TITLE
CSV-Datei mit Zeilen ohne Datumswerte

### ISSUE THREAD

**Issue by egdels** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#21]
CSV-Datei mit Zeilen ohne Datumswerte. Stattdessen ist der Excell-Fehlerwert "#WERT!" enthalten:

./April/RKI_COVID19_2020-04-27.csv

Erfasst das RKI die Fallzahlen tatsächlich mit Excell?

**Comment by JW-Schuetz** [comment]
Ganz sicher wird Excel benutzt! Deutschland lebt in der digitalen Steinzeit!

**Comment by CharlesStr** [comment]
Ja, in der Tat, die Dateien sind so veröffentlicht worden. Ich war bei der Datenübernahme nur noch am fluchen!  Bereitgestellt wurden die Dateien auf der Seite 
https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74
