### ISSUE TITLE
Identische Datensätze 25.03.2020 + 26.03.2020

### ISSUE THREAD

**Issue by tcg-bb90** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#30]
Erstmal vielen Dank Charles, dass du dir die Mühe machst und die Daten hier täglich aktualisierst. Das ist sehr hilfreich für eigene Analysen.
Ebenfalls Danke an egdels für das Beheben der Formatierungsfehler.

Bei den neu hinzugekommen Daten für März 2020 fällt auf, dass die Datensätze für 25.03 und 26.03. identisch sind (nur Datenstand ändert sich, alle anderen Variablen unverändert).
Ebenso sind erst ab dem 24.03. NeuerFall/NeuerTodesfall als Spalten vorhanden. Falls hier jemand eine Lösung findet würde ich mich freuen.

**Comment by CharlesStr** [comment]
Hallo tcg-bb90, Danke für den Hinweis-. In der Tat die Datei vom 26.03.2020 ist die vom 25.03.2020. Ich werde die Daei löschen.

 Vermutlich wurden erst ab dem 24.03.2020 die Spalten NeuerFall/NeuerTodesfall in die Datei aufgenommen.

Auffällig auc, in Der Datei vom 21.03.20201 und 25.03.2021 sind Datensätze  die keinem  Bundeland zugeordnet wurde. 
(Bundeland -nicht   erhoben-)
