### ISSUE TITLE
Error invalid Path 

### ISSUE THREAD

**Issue by jodtee** [CharlesStr/CSV-Dateien-mit-Covid-19-Infektionen-#31]
Hi,

Clonen und Pullen funktioniert nicht mehr (zumindest auf Windows) . Fehlermeldung invalid path "April2021.../-Störungen: " unable to checkout

Ich vermute, der Doppelpunkt im Ordnernamen ist das Problem und ein Umbenennen sollte das korrigieren.

Danke fürs Reparieren

**Comment by jodtee** [comment]
Folgende Zeichen dürfen in Windows -Ordnern nicht verwendet werden 
<>:?/ \ * ? " |

**Comment by CharlesStr** [comment]
Hallo,

ich hab die Ueberschrift geandert. Hoffe es hilft. danke fuer den Tipp.

**Comment by jodtee** [comment]
Kann ich bestätigen.
Neu klonen und auch das pull-Update funktionieren wieder.
